# k8.yml
name: Kubernetes Deployment

on:
  workflow_run:
    workflows: ["Build and Deploy"]  # This refers to the workflow name in main.yml
    types:
      - completed
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-k8s:
    # Only run if the Build and Deploy workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
        role-session-name: GitHubActions-${{ github.run_id }}

    - name: Get workflow outputs
      run: |
        # Get the outputs from the previous workflow
        CLUSTER_NAME=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" \
          | jq -r '.outputs.cluster_name')
        ECR_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" \
          | jq -r '.outputs.ecr_repository_url')
        echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
        echo "ECR_REGISTRY=$ECR_URL" >> $GITHUB_ENV

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region us-east-1

    - name: Deploy to Kubernetes
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd aws_infra
        
        # Get cluster info
        echo "Getting cluster information..."
        ROLE_ARN=$(aws eks describe-cluster --name $CLUSTER_NAME --query 'cluster.roleArn' --output text)
        
        # Get Node IAM Role ARN
        NODE_ROLE_ARN=$(aws iam get-role --role-name ${CLUSTER_NAME}-worker-node-role --query 'Role.Arn' --output text)
        
        # Get subnet information
        SUBNET_IDS=$(aws eks describe-cluster --name $CLUSTER_NAME \
          --query 'cluster.resourcesVpcConfig.subnetIds[]' \
          --output text)
        
        # Check for existing node groups
        echo "Checking EKS node groups..."
        NODE_GROUPS=$(aws eks list-nodegroups --cluster-name $CLUSTER_NAME --query 'nodegroups[*]' --output text || echo "")
        
        if [ -z "$NODE_GROUPS" ]; then
          echo "No node groups found. Creating default node group..."
          aws eks create-nodegroup \
            --cluster-name $CLUSTER_NAME \
            --nodegroup-name default-nodegroup \
            --scaling-config minSize=1,maxSize=3,desiredSize=2 \
            --subnets $SUBNET_IDS \
            --instance-types t3.medium \
            --node-role $NODE_ROLE_ARN \
            --ami-type AL2_x86_64
          
          echo "Waiting for nodegroup to be active..."
          aws eks wait nodegroup-active \
            --cluster-name $CLUSTER_NAME \
            --nodegroup-name default-nodegroup
        fi
        
        echo "Cleaning up old deployment resources..."
        kubectl delete deployment massage-website --ignore-not-found=true
        kubectl get pods -l app=massage-website -o name | xargs -r kubectl delete --force --grace-period=0
        kubectl delete rs -l app=massage-website --ignore-not-found=true
        
        echo "Applying manifests..."
        envsubst < k8s/deployment.yml | kubectl apply -f -
        kubectl apply -f k8s/service.yml
        kubectl apply -f k8s/ingress.yml
        
        echo "Checking pod status..."
        kubectl get pods -l app=massage-website
        kubectl describe pods -l app=massage-website
        
        echo "Waiting for deployment rollout..."
        kubectl rollout status deployment/massage-website --timeout=300s